---
title: "Bismark alignment score comparison"
author: "Shelly Trigg"
date: "8/13/2019"
output: 
  html_document:
    df_print: paged
    code_folding: hide
    theme: cerulean
    highlight: tango
    toc: true
    toc_depth: 4
    toc_float: true
  word_document: default
editor_options:
  chunk_output_type: inline
---

load libraries

```{r}
library(tidyr)
library(ggplot2)

```

read in data

```{r}
data <- read.csv("/Volumes/web/metacarcinus/Salmo_Calig/analyses/20190809_100K_Salmo/bismarkASthreshold_bigger_comparison.txt", sep = "\t", header = TRUE, stringsAsFactors = FALSE)

#make sample column
data$Sample <- c(rep(1,10),rep(2,10),rep(3,10),rep(4,10),rep(5,10))
data <- data[,c(ncol(data),1:ncol(data)-1)]
```

reformat data for plotting
```{r}

STACKED_data <- gather(data,"AS", "value",3:ncol(data))
STACKED_data$AS <- gsub("AS\\.","", STACKED_data$AS)
STACKED_data$value <- gsub("\\%","", STACKED_data$value)
STACKED_data$value <- as.numeric(STACKED_data$value)
```

plot %Cs methylated in CHH context
```{r}

ggplot(STACKED_data[grep("CHH",STACKED_data$Category),], aes(x = factor(AS, levels = c("0.2","0.6", "1", "1I60", "1.2I60", "2")), y = value, group = Sample)) + geom_line(aes(color= as.factor(Sample))) + xlab("Alignment score") + ylab("Percent") + ggtitle("C methylated in CHH context") + theme_bw()

```

plot %Cs methylated in CHG context
```{r}
ggplot(STACKED_data[grep("CHG",STACKED_data$Category),], aes(x = factor(AS, levels = c("0.2","0.6", "1", "1I60", "1.2I60", "2")), y = value, group = Sample)) + geom_line(aes(color= as.factor(Sample))) + xlab("Alignment score") + ylab("Percent") + ggtitle("C methylated in CHG context") + theme_bw()

```


plot %Cs methylated in CpG context
```{r}

ggplot(STACKED_data[grep("CpG",STACKED_data$Category),], aes(x = factor(AS, levels = c("0.2","0.6", "1", "1I60", "1.2I60", "2")), y = value, group = Sample)) + geom_line(aes(color= as.factor(Sample))) + xlab("Alignment score") + ylab("Percent") + ggtitle("C methylated in CpG context") + theme_bw()

```

plot %Cs methylated in CN or CHN context
```{r}

ggplot(STACKED_data[grep("CHN",STACKED_data$Category),], aes(x =factor(AS, levels = c("0.2","0.6", "1", "1I60", "1.2I60", "2")), y = value, group = Sample)) + geom_line(aes(color= as.factor(Sample))) + xlab("Alignment score") + ylab("Percent") + ggtitle("C methylated in CN or CHN context") + theme_bw()

```

plot %mapping efficiency
```{r}

ggplot(STACKED_data[grep("Mapp",STACKED_data$Category),], aes(x = factor(AS, levels = c("0.2","0.6", "1", "1I60", "1.2I60", "2")), y = value, group = Sample)) + geom_line(aes(color= as.factor(Sample))) + xlab("Alignment score") + ylab("Percent") + ggtitle("Mapping efficiency") + theme_bw()

```

plot %sequence pairs with no alignment
```{r}

ggplot(STACKED_data[grep("condition",STACKED_data$Category),], aes(x = factor(AS, levels = c("0.2","0.6", "1", "1I60", "1.2I60", "2")), y = value/1000, group = Sample)) + geom_line(aes(color= as.factor(Sample))) + xlab("Alignment score") + ylab("% sequence pairs") + ggtitle("Number of sequence pairs with NO alignment") + theme_bw()

```


plot % sequence pairs that aligned to multiple places
```{r}

ggplot(STACKED_data[grep("uniquely",STACKED_data$Category),], aes(x = factor(AS, levels = c("0.2","0.6", "1", "1I60", "1.2I60", "2")), y = value/1000, group = Sample)) + geom_line(aes(color= as.factor(Sample))) + xlab("Alignment score") + ylab("% sequence pairs") + ggtitle("Number of sequence pairs that map to multiple places") + theme_bw()

```
